
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: "postgresql://postgres.bwpggtgfitdedhjvyegb:4qrjVj0wPqkP1RqQ@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true",
    directUrl: "postgresql://postgres.bwpggtgfitdedhjvyegb:4qrjVj0wPqkP1RqQ@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
  },
});
